# The Elephant Shed's Prometheus config

global:
  scrape_interval: 30s
  evaluation_interval: 60s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
  #    monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # scrape data from prometheus itself
  - job_name: prometheus
    scrape_interval: 300s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  # scrape data from node_exporter and sql_exporter on this machine
  - job_name: localhost
    static_configs:
      - targets: ['localhost:9100', 'localhost:9237']
