- name: Configure apache2 to use less resources
  template:
    src: templates/apache2/mpm_event.conf.j2
    dest: /etc/apache2/mods-available/mpm_event.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache